# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget LLVMHello FileCheck llvm-PerfectShuffle count not yaml-bench SampleAnalyzerPlugin CheckerDependencyHandlingAnalyzerPlugin CheckerOptionHandlingAnalyzerPlugin BugpointPasses lli-child-target llvm-jitlink-executor obj2yaml yaml2obj)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target LLVMHello
add_library(LLVMHello MODULE IMPORTED)

# Create imported target FileCheck
add_executable(FileCheck IMPORTED)

# Create imported target llvm-PerfectShuffle
add_executable(llvm-PerfectShuffle IMPORTED)

# Create imported target count
add_executable(count IMPORTED)

# Create imported target not
add_executable(not IMPORTED)

# Create imported target yaml-bench
add_executable(yaml-bench IMPORTED)

# Create imported target SampleAnalyzerPlugin
add_library(SampleAnalyzerPlugin MODULE IMPORTED)

# Create imported target CheckerDependencyHandlingAnalyzerPlugin
add_library(CheckerDependencyHandlingAnalyzerPlugin MODULE IMPORTED)

# Create imported target CheckerOptionHandlingAnalyzerPlugin
add_library(CheckerOptionHandlingAnalyzerPlugin MODULE IMPORTED)

# Create imported target BugpointPasses
add_library(BugpointPasses MODULE IMPORTED)

# Create imported target lli-child-target
add_executable(lli-child-target IMPORTED)

# Create imported target llvm-jitlink-executor
add_executable(llvm-jitlink-executor IMPORTED)
set_property(TARGET llvm-jitlink-executor PROPERTY ENABLE_EXPORTS 1)

# Create imported target obj2yaml
add_executable(obj2yaml IMPORTED)

# Create imported target yaml2obj
add_executable(yaml2obj IMPORTED)

# Import target "LLVMHello" for configuration "MinSizeRel"
set_property(TARGET LLVMHello APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(LLVMHello PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_MINSIZEREL ""
  IMPORTED_LOCATION_MINSIZEREL "/Users/peyton/UROP/CloudCompiler/llvm-project/min_build/lib/LLVMHello.dylib"
  IMPORTED_NO_SONAME_MINSIZEREL "TRUE"
  )

# Import target "FileCheck" for configuration "MinSizeRel"
set_property(TARGET FileCheck APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(FileCheck PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "/Users/peyton/UROP/CloudCompiler/llvm-project/min_build/bin/FileCheck"
  )

# Import target "llvm-PerfectShuffle" for configuration "MinSizeRel"
set_property(TARGET llvm-PerfectShuffle APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(llvm-PerfectShuffle PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "/Users/peyton/UROP/CloudCompiler/llvm-project/min_build/bin/llvm-PerfectShuffle"
  )

# Import target "count" for configuration "MinSizeRel"
set_property(TARGET count APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(count PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "/Users/peyton/UROP/CloudCompiler/llvm-project/min_build/bin/count"
  )

# Import target "not" for configuration "MinSizeRel"
set_property(TARGET not APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(not PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "/Users/peyton/UROP/CloudCompiler/llvm-project/min_build/bin/not"
  )

# Import target "yaml-bench" for configuration "MinSizeRel"
set_property(TARGET yaml-bench APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(yaml-bench PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "/Users/peyton/UROP/CloudCompiler/llvm-project/min_build/bin/yaml-bench"
  )

# Import target "SampleAnalyzerPlugin" for configuration "MinSizeRel"
set_property(TARGET SampleAnalyzerPlugin APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SampleAnalyzerPlugin PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_MINSIZEREL ""
  IMPORTED_LOCATION_MINSIZEREL "/Users/peyton/UROP/CloudCompiler/llvm-project/min_build/lib/SampleAnalyzerPlugin.dylib"
  IMPORTED_NO_SONAME_MINSIZEREL "TRUE"
  )

# Import target "CheckerDependencyHandlingAnalyzerPlugin" for configuration "MinSizeRel"
set_property(TARGET CheckerDependencyHandlingAnalyzerPlugin APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CheckerDependencyHandlingAnalyzerPlugin PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_MINSIZEREL ""
  IMPORTED_LOCATION_MINSIZEREL "/Users/peyton/UROP/CloudCompiler/llvm-project/min_build/lib/CheckerDependencyHandlingAnalyzerPlugin.dylib"
  IMPORTED_NO_SONAME_MINSIZEREL "TRUE"
  )

# Import target "CheckerOptionHandlingAnalyzerPlugin" for configuration "MinSizeRel"
set_property(TARGET CheckerOptionHandlingAnalyzerPlugin APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CheckerOptionHandlingAnalyzerPlugin PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_MINSIZEREL ""
  IMPORTED_LOCATION_MINSIZEREL "/Users/peyton/UROP/CloudCompiler/llvm-project/min_build/lib/CheckerOptionHandlingAnalyzerPlugin.dylib"
  IMPORTED_NO_SONAME_MINSIZEREL "TRUE"
  )

# Import target "BugpointPasses" for configuration "MinSizeRel"
set_property(TARGET BugpointPasses APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(BugpointPasses PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_MINSIZEREL ""
  IMPORTED_LOCATION_MINSIZEREL "/Users/peyton/UROP/CloudCompiler/llvm-project/min_build/lib/BugpointPasses.dylib"
  IMPORTED_NO_SONAME_MINSIZEREL "TRUE"
  )

# Import target "lli-child-target" for configuration "MinSizeRel"
set_property(TARGET lli-child-target APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(lli-child-target PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "/Users/peyton/UROP/CloudCompiler/llvm-project/min_build/bin/lli-child-target"
  )

# Import target "llvm-jitlink-executor" for configuration "MinSizeRel"
set_property(TARGET llvm-jitlink-executor APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(llvm-jitlink-executor PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "/Users/peyton/UROP/CloudCompiler/llvm-project/min_build/bin/llvm-jitlink-executor"
  )

# Import target "obj2yaml" for configuration "MinSizeRel"
set_property(TARGET obj2yaml APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(obj2yaml PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "/Users/peyton/UROP/CloudCompiler/llvm-project/min_build/bin/obj2yaml"
  )

# Import target "yaml2obj" for configuration "MinSizeRel"
set_property(TARGET yaml2obj APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(yaml2obj PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "/Users/peyton/UROP/CloudCompiler/llvm-project/min_build/bin/yaml2obj"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
